server:
  port: 9001
spring:
  datasource:
    url: jdbc:sqlserver://sqlservermaktum.database.windows.net:1433;database=sqldb;user=AzureUser@sqlservermaktum;password=Mysql@2020;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: AzureUser
    password: Mysql@2020
  jpa:
    hibernate:
      ddl-auto: update